In [1]:
import numpy as np

def sigmoid (x):
    #for s in np.nditer(x, op_flags=['readwrite']):
    return 1 / (1 + np.exp(-x))

def deriv_sig(x):
    return sigmoid(x)*(1-sigmoid(x))

In [2]:
input_ = np.array([[0,0,1], [1,0,1], [0,1,1], [1,1,1]])

expected = np.array([[0,1,1,0]]).T

w1 = np.array([[0.1, 0.2, 0.3, 0.4], [-0.3, -0.2, -0.1, -0.4], [0.3, 0.2, -0.1, -0.2]])

w2 = np.array([[0.3, -0.2, 0.5, -0.4]]).T

In [3]:
z1 = input_.dot(w1)
print(z1)
a1 = sigmoid(z1)
print(a1)
z2 = a1.dot(w2)
a2 = sigmoid(z2)
print(a2)
c1 = 0.5*(a2-expected)**2   # changed from a2-1
print (c1)

[[ 0.3  0.2 -0.1 -0.2]
 [ 0.4  0.4  0.2  0.2]
 [ 0.   0.  -0.2 -0.6]
 [ 0.1  0.2  0.1 -0.2]]
[[ 0.57444252  0.549834    0.47502081  0.450166  ]
 [ 0.59868766  0.59868766  0.549834    0.549834  ]
 [ 0.5         0.5         0.450166    0.35434369]
 [ 0.52497919  0.549834    0.52497919  0.450166  ]]
[[ 0.52991671]
 [ 0.52868152]
 [ 0.53328707]
 [ 0.5324419 ]]
[[ 0.14040586]
 [ 0.11107055]
 [ 0.10891048]
 [ 0.14174719]]


In [4]:
da2 = (a2-expected)
print (da2)

[[ 0.52991671]
 [-0.47131848]
 [-0.46671293]
 [ 0.5324419 ]]


In [5]:
dz2 = (da2*deriv_sig(z2))
print (dz2)

[[ 0.1320049 ]
 [-0.1174419 ]
 [-0.1161611 ]
 [ 0.13255009]]


In [7]:
da1 = dz2.dot(w2.T)  # changed from w2.T*dz2
print (da1)

[[ 0.03960147 -0.02640098  0.06600245 -0.05280196]
 [-0.03523257  0.02348838 -0.05872095  0.04697676]
 [-0.03484833  0.02323222 -0.05808055  0.04646444]
 [ 0.03976503 -0.02651002  0.06627505 -0.05302004]]


In [8]:
dz1 = da1*deriv_sig(z1)
print (dz1)

[[ 0.00968091 -0.00653468  0.01645943 -0.01306936]
 [-0.008465    0.00564334 -0.01453441  0.01162753]
 [-0.00871208  0.00580806 -0.0143759   0.01063033]
 [ 0.00991645 -0.00656167  0.01652741 -0.01312334]]


In [9]:
dx = dz1.dot(w1.T)
print (dx)

[[-0.00062876  0.00198446  0.00256527]
 [ 0.00057285 -0.00178674 -0.0022829 ]
 [ 0.00022977 -0.00136253 -0.00214049]
 [-0.0006118   0.00193399  0.00263453]]


In [14]:
# changed from dz2*a1. dz2 is actually a vector containing all the gradients of the different input x.
# so dw2 is actuall the sum of all the gradients
dw2 = a1.T.dot(dz2) 
print (dw2)

[[ 0.0170237 ]
 [ 0.01706976]
 [ 0.01542579]
 [ 0.01335916]]


In [13]:
dw1 = input_.T.dot(dz1) # again, dw1 is the sum of all the gradients.
print (dw1)

[[ 0.00145144 -0.00091833  0.001993   -0.00149581]
 [ 0.00120436 -0.00075361  0.00215151 -0.00249301]
 [ 0.00242027 -0.00164496  0.00407653 -0.00393484]]
